[nats]
hosts = ["nats"]

# An optional token is allowed for token authentication.
# auth = { token = "my-secret-token" }

[scheduler]

[dns]
port = 53
soa_email = "hickorystevens3@gmail.com"
domain_name = "taishan.website"